const DATA = {
  stage1: {
    tasks: [
      { id:"t1", title:"Task 1 – Deploy Node.js App on ECS Fargate with ECR",
        summary:"Containerised a Node.js application, pushed the image to Amazon ECR, and deployed it on ECS Fargate with a load-balanced service.",
        tools:["Docker","Amazon ECR","ECS Fargate","ALB","IAM"], status:"Completed" },
      { id:"t2", title:"Task 2 – CI/CD with Jenkins Pipelines (Tag-Based)",
        summary:"Set up tag-based Jenkins pipelines to automate build, test, and deploy stages triggered on Git tag pushes.",
        tools:["Jenkins","GitHub","Docker","EC2"], status:"Completed" },
      { id:"t3", title:"Task 3 – Automate Deployment + Database Backup",
        summary:"Wrote shell scripts to automate application deployment and scheduled database backups using cron jobs on EC2.",
        tools:["Bash","Cron","EC2","MySQL","S3"], status:"Completed" },
      { id:"t4", title:"Task 4 – Deploying Frontend Apps on EC2, ECS, and S3",
        summary:"Compared and deployed the same frontend application across three AWS hosting options: EC2, ECS, and S3 static hosting.",
        tools:["EC2","ECS","S3","CloudFront","Nginx"], status:"Completed" },
      { id:"t5", title:"Task 5 – Deploy Full-Stack App on AWS + Automate Deployments",
        summary:"Deployed a frontend + backend application on AWS and automated the deployment pipeline end-to-end.",
        tools:["EC2","RDS","Nginx","Jenkins","GitHub Actions"], status:"Completed" },
      { id:"t6", title:"Task 6 – Multiple Frontend Apps on Apache with SSL",
        summary:"Hosted multiple frontend apps on a single Apache server using subdomain-based virtual hosting with Let's Encrypt SSL.",
        tools:["Apache","Let's Encrypt","Certbot","Route 53","EC2"], status:"Completed" },
      { id:"t7", title:"Task 7 – Temp Directory Monitoring (Lambda → Pushgateway → Grafana)",
        summary:"Built an automated monitoring pipeline using AWS Lambda to count files in /tmp, push metrics to Prometheus Pushgateway, and visualise in Grafana.",
        tools:["AWS Lambda","Prometheus","Pushgateway","Grafana","Python"], status:"Completed" },
      { id:"t8", title:"Task 8 – AWS RDS Setup and Grafana Cloud Dashboards",
        summary:"Provisioned an RDS MySQL instance, connected it to an application, and built Grafana Cloud dashboards for data visualisation.",
        tools:["AWS RDS","MySQL","Grafana Cloud","EC2","Python"], status:"Completed" },
      { id:"t9", title:"Task 9 – VM-Based and Serverless Architectures on AWS",
        summary:"Deployed the same application using both EC2 (VM-based) and AWS Lambda (serverless) and compared the two approaches.",
        tools:["EC2","AWS Lambda","API Gateway","S3","CloudWatch"], status:"Completed" },
      { id:"t10", title:"Task 10 – Custom Dashboard in CloudWatch",
        summary:"Created a custom CloudWatch dashboard with widgets for EC2 CPU, memory, network metrics, and Lambda invocation stats.",
        tools:["CloudWatch","EC2","Lambda","SNS","IAM"], status:"Completed" }
    ],
    practicals: [
      { id:"p1", title:"Practical 1 – 2-Tier Flask-MySQL Application Deployment",
        summary:"Deployed a two-tier Flask + MySQL application on AWS EC2, covering environment setup, database configuration, and application hosting.",
        tools:["Flask","MySQL","EC2","Nginx","Python"], status:"Completed" }
    ],
    labs: [
      { id:"l1", title:"Lab – EC2 Instance Setup & SSH Access",
        summary:"Hands-on lab covering EC2 instance provisioning, security group configuration, key-pair management, and SSH access.",
        tools:["EC2","SSH","Security Groups","IAM"], status:"Completed" },
      { id:"l2", title:"Lab – Docker Basics & Containerisation",
        summary:"Introduction to Docker: writing Dockerfiles, building images, running containers, and pushing to a registry.",
        tools:["Docker","DockerHub","Linux"], status:"Completed" },
      { id:"l3", title:"Lab – S3 Static Website Hosting",
        summary:"Configured an S3 bucket for static website hosting with public access policies and CloudFront distribution.",
        tools:["S3","CloudFront","IAM","Route 53"], status:"Completed" }
    ],
    theory: [
      { id:"th1", title:"Theory – EC2 vs ECS vs S3 Hosting Comparison",
        summary:"Research document comparing Amazon EC2, ECS, and S3 for hosting frontend applications, covering cost, scalability, and use cases.",
        tools:["EC2","ECS","S3"], status:"Completed" },
      { id:"th2", title:"Theory – Containerisation in AWS Lambda vs ECS",
        summary:"Deep-dive into how containerisation differs between AWS Lambda (ephemeral containers) and ECS (long-running containers).",
        tools:["Lambda","ECS","Docker"], status:"Completed" },
      { id:"th3", title:"Theory – TLS in Modern Web Architecture",
        summary:"Explains TLS handshake, certificate management, and how TLS is applied across load balancers, Nginx, and CDN layers.",
        tools:["TLS/SSL","Nginx","ACM","Let's Encrypt"], status:"Completed" },
      { id:"th4", title:"Theory – Serverless vs Traditional VM-Based Architecture",
        summary:"Comparison of serverless (Lambda) and VM-based (EC2) architectures covering cold starts, cost models, and operational overhead.",
        tools:["Lambda","EC2","API Gateway"], status:"Completed" }
    ]
  },

  stage2: {
    tasks: [
      { id:"t11", title:"Task 11 – Deploy 2-Tier Bookstore App on AWS",
        summary:"Deployed a full Bookstore API (Flask + database) on AWS using a two-tier architecture with proper networking and security groups.",
        tools:["Flask","RDS","EC2","ALB","VPC"], status:"Completed" },
      { id:"t12", title:"Task 12 – Monitoring Dashboards & Alerts for Bookstore API",
        summary:"Set up CloudWatch and Grafana dashboards to track HTTP error rates and status code trends for the Bookstore API.",
        tools:["CloudWatch","Grafana","Prometheus","SNS","Python"], status:"Completed" },
      { id:"t13", title:"Task 13 – Monitoring Auto-Create Script",
        summary:"Wrote an automation script to programmatically create CloudWatch alarms, dashboards, and SNS notifications for any new service.",
        tools:["Python","Boto3","CloudWatch","SNS","Bash"], status:"Completed" },
      { id:"t14", title:"Task 14 – VPC Networking Setup",
        summary:"Designed and provisioned a production-grade VPC with public/private subnets, NAT gateway, route tables, and security groups.",
        tools:["VPC","Subnets","NAT Gateway","Route Tables","IGW"], status:"Completed" },
      { id:"t15", title:"Task 15 – TLS Configuration",
        summary:"Configured end-to-end TLS for a web application using ACM certificates on ALB and self-signed certs on EC2 backend.",
        tools:["ACM","ALB","Nginx","TLS/SSL","Route 53"], status:"Completed" },
      { id:"t16", title:"Task 16 – Automate Deployment & Load Balancing with SSM (Flask + MongoDB Atlas)",
        summary:"Used AWS SSM Run Command to automate Flask app deployment across multiple EC2 instances behind an ALB, connected to MongoDB Atlas.",
        tools:["SSM","ALB","Flask","MongoDB Atlas","EC2"], status:"Completed" },
      { id:"t17", title:"Task 17 – Multi-VPC AWS Network Environment",
        summary:"Built a multi-VPC environment with VPC peering, Transit Gateway, and cross-VPC routing to simulate enterprise networking.",
        tools:["VPC Peering","Transit Gateway","Route Tables","EC2","IAM"], status:"Completed" },
      { id:"t18", title:"Task 18 – Nginx and ALB",
        summary:"Configured Nginx as a reverse proxy in front of an AWS ALB, implementing path-based routing and SSL termination.",
        tools:["Nginx","ALB","EC2","ACM","Route 53"], status:"Completed" },
      { id:"t19", title:"Task 19 – SMTP, AWS SES, and AWS WorkMail",
        summary:"Compared self-hosted SMTP, AWS SES, and AWS WorkMail; configured SES for transactional email with domain verification and DKIM.",
        tools:["AWS SES","AWS WorkMail","SMTP","Route 53","IAM"], status:"Completed" },
      { id:"t20", title:"Task 20 – Self-Hosted DNS Server and AWS Route 53",
        summary:"Set up a self-hosted BIND DNS server on EC2 and compared it with AWS Route 53 for zone management and failover routing.",
        tools:["BIND9","Route 53","EC2","DNS","VPC"], status:"Completed" },
      { id:"t21", title:"Task 21 – Azure App Service",
        summary:"Deployed a web application on Azure App Service, configured deployment slots, custom domains, and compared with AWS Elastic Beanstalk.",
        tools:["Azure App Service","Azure CLI","GitHub Actions","Docker"], status:"Completed" },
      { id:"t22", title:"Task 22 – GitLab CE Server + Flask App Push",
        summary:"Installed and configured a self-hosted GitLab CE server on EC2, created a project, and pushed a Flask Hello World application.",
        tools:["GitLab CE","EC2","Git","Flask","Nginx"], status:"Completed" },
      { id:"t23", title:"Task 23 – GitLab CE with Two Self-Hosted Runners",
        summary:"Extended the GitLab CE setup with two self-hosted runners (shell and Docker executors) and configured a CI pipeline.",
        tools:["GitLab CE","GitLab Runner","Docker","CI/CD","EC2"], status:"Completed" },
      { id:"t24", title:"Task 24 – Wrong Branch Development (Merge Mistake)",
        summary:"Simulated a real-world Git mistake (committing to wrong branch), then resolved it using rebase, cherry-pick, and force-push strategies.",
        tools:["Git","GitHub","GitLab","Rebase","Cherry-pick"], status:"Completed" },
      { id:"t25", title:"Task 25 – AWS Architecture Research & Open-Source On-Prem Alternative",
        summary:"Researched the Namma Yatri AWS architecture and designed an equivalent open-source on-premises alternative using Kubernetes and open tools.",
        tools:["Kubernetes","Prometheus","Grafana","PostgreSQL","Kafka"], status:"Completed" },
      { id:"t26", title:"Task 26 – AWS Outages Research, RCA & Video Explainer",
        summary:"Researched the AWS us-east-1 outage of December 7 2021, produced a root cause analysis document and a video explainer.",
        tools:["CloudWatch","Route 53","AWS Status","RCA"], status:"Completed" },
      { id:"t27", title:"Task 27 – AWS CUDOS Workshop Dashboard Analysis",
        summary:"Analysed the AWS CUDOS (Cloud Intelligence Dashboard) workshop, explored cost optimisation widgets and CUR data integration.",
        tools:["AWS Cost Explorer","QuickSight","CUR","Athena","S3"], status:"Completed" },
      { id:"t28", title:"Task 28 – AWS Managed Prometheus vs EC2-Hosted Prometheus",
        summary:"Compared AWS Managed Prometheus (AMP) with a self-hosted Prometheus on EC2 for server monitoring metrics, cost, and operational effort.",
        tools:["AWS AMP","Prometheus","Grafana","EC2","IAM"], status:"Completed" },
      { id:"t29", title:"Task 29 – AWS Security Hub Overview & Findings Remediation",
        summary:"Enabled AWS Security Hub, reviewed CIS benchmark findings, and remediated high-severity security issues across EC2 and IAM.",
        tools:["Security Hub","GuardDuty","IAM","EC2","Config"], status:"Completed" },
      { id:"t30", title:"Task 30 – Frontend Showcase (Stage 1 & Stage 2) Using AWS Kiro",
        summary:"Built this single-page frontend portal to showcase all tasks, practicals, labs, and theory from Stage 1 and Stage 2 using AWS Kiro.",
        tools:["HTML","CSS","JavaScript","AWS Kiro","GitHub"], status:"Completed" }
    ],
    practicals: [
      { id:"p2", title:"Practical 2 – Two-Tier Flask & MySQL Deployment Plan",
        summary:"Produced a full deployment plan for a two-tier Flask + MySQL application on AWS, covering architecture, rollback strategy, and runbook.",
        tools:["Flask","MySQL","EC2","RDS","ALB"], status:"Completed" },
      { id:"p3", title:"Practical 3 – DevOps Project Documentation (Flask on AWS)",
        summary:"End-to-end DevOps project documentation for deploying a Flask application on AWS including CI/CD, monitoring, and security.",
        tools:["Flask","Jenkins","Docker","CloudWatch","RDS"], status:"Completed" }
    ],
    labs: [
      { id:"l4", title:"Lab – VPC Design and Subnet Planning",
        summary:"Hands-on lab designing a VPC with CIDR allocation, public/private subnets across multiple AZs, and NAT gateway setup.",
        tools:["VPC","Subnets","NAT Gateway","Route Tables"], status:"Completed" },
      { id:"l5", title:"Lab – GitLab CI/CD Pipeline",
        summary:"Configured a full GitLab CI/CD pipeline with build, test, and deploy stages using self-hosted runners.",
        tools:["GitLab CI","Docker","GitLab Runner","EC2"], status:"Completed" },
      { id:"l6", title:"Lab – CloudWatch Alarms and SNS Notifications",
        summary:"Created CloudWatch metric alarms for EC2 and Lambda, wired to SNS topics for email and Slack notifications.",
        tools:["CloudWatch","SNS","Lambda","EC2"], status:"Completed" }
    ],
    theory: [
      { id:"th5", title:"Theory – SQL vs NoSQL in Bookstore API Deployment",
        summary:"Compared relational (MySQL/RDS) and non-relational (MongoDB) databases in the context of the Bookstore API, covering schema design and query patterns.",
        tools:["MySQL","MongoDB","RDS","DynamoDB"], status:"Completed" },
      { id:"th6", title:"Theory – Nginx and AWS ALB Deep Dive",
        summary:"Detailed comparison of Nginx reverse proxy and AWS ALB, covering Layer 4 vs Layer 7 routing, health checks, and SSL offloading.",
        tools:["Nginx","ALB","TLS/SSL","Route 53"], status:"Completed" },
      { id:"th7", title:"Theory – Mail Server vs AWS SES vs AWS WorkMail",
        summary:"Compared self-hosted mail servers (Postfix), AWS SES for transactional email, and AWS WorkMail for corporate email hosting.",
        tools:["AWS SES","AWS WorkMail","Postfix","SMTP","DKIM"], status:"Completed" },
      { id:"th8", title:"Theory – AWS Route 53 vs Self-Hosted DNS",
        summary:"Evaluated AWS Route 53 managed DNS against a self-hosted BIND9 server, covering latency routing, failover, and cost.",
        tools:["Route 53","BIND9","DNS","EC2"], status:"Completed" },
      { id:"th9", title:"Theory – SOA Record vs TXT Record",
        summary:"Explained the difference between DNS SOA (Start of Authority) and TXT records, their structure, and use cases in AWS Route 53.",
        tools:["DNS","Route 53"], status:"Completed" },
      { id:"th10", title:"Theory – Scripting vs Manual Execution",
        summary:"Discussed the advantages of automation scripts over manual CLI execution for monitoring setup, deployment, and incident response.",
        tools:["Bash","Python","Boto3"], status:"Completed" },
      { id:"th11", title:"Theory – IP Model and Networking Concepts",
        summary:"Covered the TCP/IP model layers, subnetting, CIDR notation, and how AWS VPC maps to traditional networking concepts.",
        tools:["TCP/IP","VPC","Subnets","CIDR"], status:"Completed" },
      { id:"th12", title:"Theory – AWS Networking Concepts",
        summary:"Comprehensive overview of AWS networking: VPC, peering, Transit Gateway, Direct Connect, PrivateLink, and security groups.",
        tools:["VPC","Transit Gateway","Direct Connect","PrivateLink"], status:"Completed" },
      { id:"th13", title:"Theory – API Monitoring: Error Rate & Status Code Tracking",
        summary:"Best practices for monitoring REST APIs using CloudWatch and Grafana, focusing on 4xx/5xx error rates and latency percentiles.",
        tools:["CloudWatch","Grafana","Prometheus","API Gateway"], status:"Completed" }
    ]
  }
};
